/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminNotification {
  'id' : bigint,
  'customerName' : string,
  'customerPrincipal' : Principal,
  'read' : boolean,
  'propertyTitle' : string,
  'leadId' : bigint,
  'timestamp' : Time,
  'category' : ListingCategory,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AvailabilityCounts {
  'marriageHalls' : bigint,
  'hotels' : bigint,
  'pgRooms' : bigint,
  'familyFlats' : bigint,
}
export interface AvailabilityStatus {
  'unitType' : string,
  'status' : { 'partiallyAvailable' : null } |
    { 'booked' : null } |
    { 'available' : null },
  'availableUnits' : bigint,
  'dates' : [] | [Array<{ 'date' : Time, 'availableUnits' : bigint }>],
}
export interface CityChargeSettings {
  'subscription' : boolean,
  'customerLeadCharge' : boolean,
  'ownerLeadCharge' : boolean,
}
export interface CreatePaymentResponse {
  'checkoutUrl' : string,
  'sessionId' : string,
}
export interface EventMarker {
  'id' : bigint,
  'createdAt' : Time,
  'type' : string,
  'message' : string,
  'badge' : string,
  'location' : GeoLocation,
}
export type ExternalBlob = Uint8Array;
export interface GeoLocation {
  'lat' : number,
  'lon' : number,
  'address' : string,
}
export interface LeadView {
  'id' : bigint,
  'propertyCategory' : ListingCategory,
  'propertyArea' : string,
  'ownerName' : string,
  'listingId' : bigint,
  'ownerPrincipal' : Principal,
  'viewerName' : string,
  'propertyTitle' : string,
  'ownerContact' : string,
  'timestamp' : Time,
  'viewer' : Principal,
}
export interface Listing {
  'id' : bigint,
  'title' : string,
  'verified' : boolean,
  'featured' : boolean,
  'contactInfo' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'description' : string,
  'approvalStatus' : ApprovalStatus,
  'pricePerDay' : bigint,
  'availability' : AvailabilityStatus,
  'category' : ListingCategory,
  'propertyStatus' : PropertyStatus,
  'location' : GeoLocation,
  'statusTimestamp' : Time,
  'images' : Array<ExternalBlob>,
}
export type ListingCategory = { 'marriageHall' : null } |
  { 'studentStay' : null } |
  { 'hotel' : null } |
  { 'travelStay' : null } |
  { 'pgHostel' : null } |
  { 'familyFlat' : null } |
  { 'eventSpace' : null };
export interface OwnerProfile {
  'verified' : boolean,
  'ownerId' : Principal,
  'name' : string,
  'joinedAt' : Time,
  'email' : string,
  'contactNumber' : string,
}
export interface PaymentCancelResponse {
  'message' : string,
  'sessionId' : string,
}
export interface PaymentSuccessResponse {
  'message' : string,
  'payment' : {
    'status' : string,
    'paymentMethod' : { 'last4' : string, 'brand' : string },
    'currency' : string,
    'amount' : bigint,
  },
}
export type PropertyStatus = { 'bookedViaSTYO' : null } |
  { 'available' : null } |
  { 'visitCompleted' : null } |
  { 'underConfirmation' : null };
export interface PublicListingInput {
  'ownerEmail' : string,
  'title' : string,
  'contactInfo' : string,
  'ownerName' : string,
  'description' : string,
  'pricePerDay' : bigint,
  'availability' : AvailabilityStatus,
  'category' : ListingCategory,
  'location' : GeoLocation,
  'ownerContactNumber' : string,
  'images' : Array<ExternalBlob>,
}
export interface PublicListingSubmission {
  'ownerId' : Principal,
  'listingId' : bigint,
  'ownerProfile' : OwnerProfile,
}
export interface QuickPublishResult {
  'cacheHits' : bigint,
  'optimizationCycles' : bigint,
  'cacheMisses' : bigint,
  'frontendDeploymentTimeMs' : bigint,
  'success' : boolean,
  'backendSyncTimeMs' : bigint,
  'assetsValidated' : bigint,
  'assetsCached' : bigint,
  'buildTimeTotalNs' : bigint,
}
export interface Review {
  'id' : bigint,
  'listingId' : bigint,
  'createdAt' : Time,
  'comment' : string,
  'rating' : bigint,
  'reviewer' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
  'registrationDate' : Time,
  'lastLogin' : Time,
  'isOwner' : boolean,
  'location' : [] | [GeoLocation],
  'ipAddress' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[bigint, bigint, string], bigint>,
  'approveListing' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateCityCharges' : ActorMethod<
    [Array<[string, CityChargeSettings]>],
    undefined
  >,
  'checkoutBookingHold' : ActorMethod<[], CreatePaymentResponse>,
  'checkoutFeaturedListing' : ActorMethod<[], CreatePaymentResponse>,
  'checkoutPropertyListing' : ActorMethod<[], CreatePaymentResponse>,
  'checkoutUnlockOwnerInfo' : ActorMethod<[], CreatePaymentResponse>,
  'createBooking' : ActorMethod<[bigint, Time, Time], bigint>,
  'createListing' : ActorMethod<
    [
      string,
      string,
      ListingCategory,
      bigint,
      Array<ExternalBlob>,
      GeoLocation,
      AvailabilityStatus,
      string,
    ],
    bigint
  >,
  'createOwnerUnlockRequest' : ActorMethod<[bigint], bigint>,
  'getAdminDashboardData' : ActorMethod<
    [],
    {
      'leadViews' : Array<LeadView>,
      'notifications' : Array<AdminNotification>,
      'listings' : Array<Listing>,
      'users' : Array<UserProfile>,
      'cityCharges' : Array<[string, CityChargeSettings]>,
    }
  >,
  'getAdminNotifications' : ActorMethod<[], Array<AdminNotification>>,
  'getAllListingsForReview' : ActorMethod<[], Array<Listing>>,
  'getAvailability' : ActorMethod<[bigint], [] | [AvailabilityStatus]>,
  'getAvailabilityCounts' : ActorMethod<[], AvailabilityCounts>,
  'getAvailableListings' : ActorMethod<[], Array<Listing>>,
  'getAverageRating' : ActorMethod<[bigint], [] | [number]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChargeStatusForCity' : ActorMethod<[string], CityChargeSettings>,
  'getCityChargeSettings' : ActorMethod<
    [],
    Array<[string, CityChargeSettings]>
  >,
  'getEventMarkers' : ActorMethod<[], Array<EventMarker>>,
  'getFeaturedListings' : ActorMethod<[], Array<Listing>>,
  'getLeadAnalytics' : ActorMethod<[], Array<LeadView>>,
  'getListing' : ActorMethod<[bigint], [] | [Listing]>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'getListingsByApprovalStatus' : ActorMethod<[ApprovalStatus], Array<Listing>>,
  'getListingsByCategory' : ActorMethod<[ListingCategory], Array<Listing>>,
  'getListingsByLocation' : ActorMethod<
    [number, number, [] | [number]],
    Array<Listing>
  >,
  'getPendingSubmissions' : ActorMethod<
    [],
    Array<[bigint, PublicListingSubmission]>
  >,
  'getReviewsForListing' : ActorMethod<[bigint], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedListings' : ActorMethod<[], Array<Listing>>,
  'initializeStripePrices' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFreeTrialMode' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'paymentCancel' : ActorMethod<[string], PaymentCancelResponse>,
  'paymentSuccess' : ActorMethod<
    [string, string, string],
    PaymentSuccessResponse
  >,
  'processExpiredListings' : ActorMethod<[], bigint>,
  'quickPublishMode' : ActorMethod<[], QuickPublishResult>,
  'rejectListing' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFreeTrialMode' : ActorMethod<[boolean], undefined>,
  'submitPublicListing' : ActorMethod<[PublicListingInput], bigint>,
  'updateAvailability' : ActorMethod<[bigint, AvailabilityStatus], undefined>,
  'updateCityChargeSettings' : ActorMethod<
    [string, CityChargeSettings],
    undefined
  >,
  'updateListing' : ActorMethod<[bigint, Listing], undefined>,
  'updateOwnerProfile' : ActorMethod<[OwnerProfile], undefined>,
  'updatePropertyStatus' : ActorMethod<[bigint, PropertyStatus], undefined>,
  'verifyListing' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];