/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CityChargeSettings = IDL.Record({
  'subscription' : IDL.Bool,
  'customerLeadCharge' : IDL.Bool,
  'ownerLeadCharge' : IDL.Bool,
});
export const CreatePaymentResponse = IDL.Record({
  'checkoutUrl' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const Time = IDL.Int;
export const ListingCategory = IDL.Variant({
  'marriageHall' : IDL.Null,
  'studentStay' : IDL.Null,
  'hotel' : IDL.Null,
  'travelStay' : IDL.Null,
  'pgHostel' : IDL.Null,
  'familyFlat' : IDL.Null,
  'eventSpace' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GeoLocation = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'address' : IDL.Text,
});
export const AvailabilityStatus = IDL.Record({
  'unitType' : IDL.Text,
  'status' : IDL.Variant({
    'partiallyAvailable' : IDL.Null,
    'booked' : IDL.Null,
    'available' : IDL.Null,
  }),
  'availableUnits' : IDL.Nat,
  'dates' : IDL.Opt(
    IDL.Vec(IDL.Record({ 'date' : Time, 'availableUnits' : IDL.Nat }))
  ),
});
export const LeadView = IDL.Record({
  'id' : IDL.Nat,
  'propertyCategory' : ListingCategory,
  'propertyArea' : IDL.Text,
  'ownerName' : IDL.Text,
  'listingId' : IDL.Nat,
  'ownerPrincipal' : IDL.Principal,
  'viewerName' : IDL.Text,
  'propertyTitle' : IDL.Text,
  'ownerContact' : IDL.Text,
  'timestamp' : Time,
  'viewer' : IDL.Principal,
});
export const AdminNotification = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'customerPrincipal' : IDL.Principal,
  'read' : IDL.Bool,
  'propertyTitle' : IDL.Text,
  'leadId' : IDL.Nat,
  'timestamp' : Time,
  'category' : ListingCategory,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PropertyStatus = IDL.Variant({
  'bookedViaSTYO' : IDL.Null,
  'available' : IDL.Null,
  'visitCompleted' : IDL.Null,
  'underConfirmation' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'verified' : IDL.Bool,
  'featured' : IDL.Bool,
  'contactInfo' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'description' : IDL.Text,
  'approvalStatus' : ApprovalStatus,
  'pricePerDay' : IDL.Nat,
  'availability' : AvailabilityStatus,
  'category' : ListingCategory,
  'propertyStatus' : PropertyStatus,
  'location' : GeoLocation,
  'statusTimestamp' : Time,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'registrationDate' : Time,
  'lastLogin' : Time,
  'isOwner' : IDL.Bool,
  'location' : IDL.Opt(GeoLocation),
  'ipAddress' : IDL.Text,
});
export const AvailabilityCounts = IDL.Record({
  'marriageHalls' : IDL.Nat,
  'hotels' : IDL.Nat,
  'pgRooms' : IDL.Nat,
  'familyFlats' : IDL.Nat,
});
export const EventMarker = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'type' : IDL.Text,
  'message' : IDL.Text,
  'badge' : IDL.Text,
  'location' : GeoLocation,
});
export const OwnerProfile = IDL.Record({
  'verified' : IDL.Bool,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'joinedAt' : Time,
  'email' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const PublicListingSubmission = IDL.Record({
  'ownerId' : IDL.Principal,
  'listingId' : IDL.Nat,
  'ownerProfile' : OwnerProfile,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'listingId' : IDL.Nat,
  'createdAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});
export const PaymentCancelResponse = IDL.Record({
  'message' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const PaymentSuccessResponse = IDL.Record({
  'message' : IDL.Text,
  'payment' : IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  }),
});
export const QuickPublishResult = IDL.Record({
  'cacheHits' : IDL.Nat,
  'optimizationCycles' : IDL.Nat,
  'cacheMisses' : IDL.Nat,
  'frontendDeploymentTimeMs' : IDL.Nat,
  'success' : IDL.Bool,
  'backendSyncTimeMs' : IDL.Nat,
  'assetsValidated' : IDL.Nat,
  'assetsCached' : IDL.Nat,
  'buildTimeTotalNs' : IDL.Nat,
});
export const PublicListingInput = IDL.Record({
  'ownerEmail' : IDL.Text,
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'ownerName' : IDL.Text,
  'description' : IDL.Text,
  'pricePerDay' : IDL.Nat,
  'availability' : AvailabilityStatus,
  'category' : ListingCategory,
  'location' : GeoLocation,
  'ownerContactNumber' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'approveListing' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateCityCharges' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, CityChargeSettings))],
      [],
      [],
    ),
  'checkoutBookingHold' : IDL.Func([], [CreatePaymentResponse], []),
  'checkoutFeaturedListing' : IDL.Func([], [CreatePaymentResponse], []),
  'checkoutPropertyListing' : IDL.Func([], [CreatePaymentResponse], []),
  'checkoutUnlockOwnerInfo' : IDL.Func([], [CreatePaymentResponse], []),
  'createBooking' : IDL.Func([IDL.Nat, Time, Time], [IDL.Nat], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ListingCategory,
        IDL.Nat,
        IDL.Vec(ExternalBlob),
        GeoLocation,
        AvailabilityStatus,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createOwnerUnlockRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getAdminDashboardData' : IDL.Func(
      [],
      [
        IDL.Record({
          'leadViews' : IDL.Vec(LeadView),
          'notifications' : IDL.Vec(AdminNotification),
          'listings' : IDL.Vec(Listing),
          'users' : IDL.Vec(UserProfile),
          'cityCharges' : IDL.Vec(IDL.Tuple(IDL.Text, CityChargeSettings)),
        }),
      ],
      ['query'],
    ),
  'getAdminNotifications' : IDL.Func(
      [],
      [IDL.Vec(AdminNotification)],
      ['query'],
    ),
  'getAllListingsForReview' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAvailability' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AvailabilityStatus)],
      ['query'],
    ),
  'getAvailabilityCounts' : IDL.Func([], [AvailabilityCounts], ['query']),
  'getAvailableListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Float64)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChargeStatusForCity' : IDL.Func(
      [IDL.Text],
      [CityChargeSettings],
      ['query'],
    ),
  'getCityChargeSettings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, CityChargeSettings))],
      ['query'],
    ),
  'getEventMarkers' : IDL.Func([], [IDL.Vec(EventMarker)], ['query']),
  'getFeaturedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getLeadAnalytics' : IDL.Func([], [IDL.Vec(LeadView)], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getListingsByApprovalStatus' : IDL.Func(
      [ApprovalStatus],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getListingsByCategory' : IDL.Func(
      [ListingCategory],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getListingsByLocation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Opt(IDL.Float64)],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getPendingSubmissions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PublicListingSubmission))],
      ['query'],
    ),
  'getReviewsForListing' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'initializeStripePrices' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFreeTrialMode' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
  'paymentSuccess' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PaymentSuccessResponse],
      [],
    ),
  'processExpiredListings' : IDL.Func([], [IDL.Nat], []),
  'quickPublishMode' : IDL.Func([], [QuickPublishResult], []),
  'rejectListing' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFreeTrialMode' : IDL.Func([IDL.Bool], [], []),
  'submitPublicListing' : IDL.Func([PublicListingInput], [IDL.Nat], []),
  'updateAvailability' : IDL.Func([IDL.Nat, AvailabilityStatus], [], []),
  'updateCityChargeSettings' : IDL.Func([IDL.Text, CityChargeSettings], [], []),
  'updateListing' : IDL.Func([IDL.Nat, Listing], [], []),
  'updateOwnerProfile' : IDL.Func([OwnerProfile], [], []),
  'updatePropertyStatus' : IDL.Func([IDL.Nat, PropertyStatus], [], []),
  'verifyListing' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CityChargeSettings = IDL.Record({
    'subscription' : IDL.Bool,
    'customerLeadCharge' : IDL.Bool,
    'ownerLeadCharge' : IDL.Bool,
  });
  const CreatePaymentResponse = IDL.Record({
    'checkoutUrl' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const Time = IDL.Int;
  const ListingCategory = IDL.Variant({
    'marriageHall' : IDL.Null,
    'studentStay' : IDL.Null,
    'hotel' : IDL.Null,
    'travelStay' : IDL.Null,
    'pgHostel' : IDL.Null,
    'familyFlat' : IDL.Null,
    'eventSpace' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GeoLocation = IDL.Record({
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'address' : IDL.Text,
  });
  const AvailabilityStatus = IDL.Record({
    'unitType' : IDL.Text,
    'status' : IDL.Variant({
      'partiallyAvailable' : IDL.Null,
      'booked' : IDL.Null,
      'available' : IDL.Null,
    }),
    'availableUnits' : IDL.Nat,
    'dates' : IDL.Opt(
      IDL.Vec(IDL.Record({ 'date' : Time, 'availableUnits' : IDL.Nat }))
    ),
  });
  const LeadView = IDL.Record({
    'id' : IDL.Nat,
    'propertyCategory' : ListingCategory,
    'propertyArea' : IDL.Text,
    'ownerName' : IDL.Text,
    'listingId' : IDL.Nat,
    'ownerPrincipal' : IDL.Principal,
    'viewerName' : IDL.Text,
    'propertyTitle' : IDL.Text,
    'ownerContact' : IDL.Text,
    'timestamp' : Time,
    'viewer' : IDL.Principal,
  });
  const AdminNotification = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'customerPrincipal' : IDL.Principal,
    'read' : IDL.Bool,
    'propertyTitle' : IDL.Text,
    'leadId' : IDL.Nat,
    'timestamp' : Time,
    'category' : ListingCategory,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PropertyStatus = IDL.Variant({
    'bookedViaSTYO' : IDL.Null,
    'available' : IDL.Null,
    'visitCompleted' : IDL.Null,
    'underConfirmation' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'verified' : IDL.Bool,
    'featured' : IDL.Bool,
    'contactInfo' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'description' : IDL.Text,
    'approvalStatus' : ApprovalStatus,
    'pricePerDay' : IDL.Nat,
    'availability' : AvailabilityStatus,
    'category' : ListingCategory,
    'propertyStatus' : PropertyStatus,
    'location' : GeoLocation,
    'statusTimestamp' : Time,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'registrationDate' : Time,
    'lastLogin' : Time,
    'isOwner' : IDL.Bool,
    'location' : IDL.Opt(GeoLocation),
    'ipAddress' : IDL.Text,
  });
  const AvailabilityCounts = IDL.Record({
    'marriageHalls' : IDL.Nat,
    'hotels' : IDL.Nat,
    'pgRooms' : IDL.Nat,
    'familyFlats' : IDL.Nat,
  });
  const EventMarker = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'type' : IDL.Text,
    'message' : IDL.Text,
    'badge' : IDL.Text,
    'location' : GeoLocation,
  });
  const OwnerProfile = IDL.Record({
    'verified' : IDL.Bool,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'joinedAt' : Time,
    'email' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const PublicListingSubmission = IDL.Record({
    'ownerId' : IDL.Principal,
    'listingId' : IDL.Nat,
    'ownerProfile' : OwnerProfile,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'listingId' : IDL.Nat,
    'createdAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  const PaymentCancelResponse = IDL.Record({
    'message' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const PaymentSuccessResponse = IDL.Record({
    'message' : IDL.Text,
    'payment' : IDL.Record({
      'status' : IDL.Text,
      'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
      'currency' : IDL.Text,
      'amount' : IDL.Nat,
    }),
  });
  const QuickPublishResult = IDL.Record({
    'cacheHits' : IDL.Nat,
    'optimizationCycles' : IDL.Nat,
    'cacheMisses' : IDL.Nat,
    'frontendDeploymentTimeMs' : IDL.Nat,
    'success' : IDL.Bool,
    'backendSyncTimeMs' : IDL.Nat,
    'assetsValidated' : IDL.Nat,
    'assetsCached' : IDL.Nat,
    'buildTimeTotalNs' : IDL.Nat,
  });
  const PublicListingInput = IDL.Record({
    'ownerEmail' : IDL.Text,
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'ownerName' : IDL.Text,
    'description' : IDL.Text,
    'pricePerDay' : IDL.Nat,
    'availability' : AvailabilityStatus,
    'category' : ListingCategory,
    'location' : GeoLocation,
    'ownerContactNumber' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'approveListing' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateCityCharges' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, CityChargeSettings))],
        [],
        [],
      ),
    'checkoutBookingHold' : IDL.Func([], [CreatePaymentResponse], []),
    'checkoutFeaturedListing' : IDL.Func([], [CreatePaymentResponse], []),
    'checkoutPropertyListing' : IDL.Func([], [CreatePaymentResponse], []),
    'checkoutUnlockOwnerInfo' : IDL.Func([], [CreatePaymentResponse], []),
    'createBooking' : IDL.Func([IDL.Nat, Time, Time], [IDL.Nat], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ListingCategory,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
          GeoLocation,
          AvailabilityStatus,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createOwnerUnlockRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getAdminDashboardData' : IDL.Func(
        [],
        [
          IDL.Record({
            'leadViews' : IDL.Vec(LeadView),
            'notifications' : IDL.Vec(AdminNotification),
            'listings' : IDL.Vec(Listing),
            'users' : IDL.Vec(UserProfile),
            'cityCharges' : IDL.Vec(IDL.Tuple(IDL.Text, CityChargeSettings)),
          }),
        ],
        ['query'],
      ),
    'getAdminNotifications' : IDL.Func(
        [],
        [IDL.Vec(AdminNotification)],
        ['query'],
      ),
    'getAllListingsForReview' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAvailability' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AvailabilityStatus)],
        ['query'],
      ),
    'getAvailabilityCounts' : IDL.Func([], [AvailabilityCounts], ['query']),
    'getAvailableListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Float64)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChargeStatusForCity' : IDL.Func(
        [IDL.Text],
        [CityChargeSettings],
        ['query'],
      ),
    'getCityChargeSettings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, CityChargeSettings))],
        ['query'],
      ),
    'getEventMarkers' : IDL.Func([], [IDL.Vec(EventMarker)], ['query']),
    'getFeaturedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getLeadAnalytics' : IDL.Func([], [IDL.Vec(LeadView)], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getListingsByApprovalStatus' : IDL.Func(
        [ApprovalStatus],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getListingsByCategory' : IDL.Func(
        [ListingCategory],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getListingsByLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Opt(IDL.Float64)],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getPendingSubmissions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PublicListingSubmission))],
        ['query'],
      ),
    'getReviewsForListing' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'initializeStripePrices' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFreeTrialMode' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
    'paymentSuccess' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PaymentSuccessResponse],
        [],
      ),
    'processExpiredListings' : IDL.Func([], [IDL.Nat], []),
    'quickPublishMode' : IDL.Func([], [QuickPublishResult], []),
    'rejectListing' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFreeTrialMode' : IDL.Func([IDL.Bool], [], []),
    'submitPublicListing' : IDL.Func([PublicListingInput], [IDL.Nat], []),
    'updateAvailability' : IDL.Func([IDL.Nat, AvailabilityStatus], [], []),
    'updateCityChargeSettings' : IDL.Func(
        [IDL.Text, CityChargeSettings],
        [],
        [],
      ),
    'updateListing' : IDL.Func([IDL.Nat, Listing], [], []),
    'updateOwnerProfile' : IDL.Func([OwnerProfile], [], []),
    'updatePropertyStatus' : IDL.Func([IDL.Nat, PropertyStatus], [], []),
    'verifyListing' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };