/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Review {
    id: bigint;
    listingId: bigint;
    createdAt: Time;
    comment: string;
    rating: bigint;
    reviewer: Principal;
}
export interface GeoLocation {
    lat: number;
    lon: number;
    address: string;
}
export type Time = bigint;
export interface Listing {
    id: bigint;
    title: string;
    verified: boolean;
    featured: boolean;
    contactInfo: string;
    owner: Principal;
    createdAt: Time;
    lastUpdated: Time;
    description: string;
    approvalStatus: ApprovalStatus;
    pricePerDay: bigint;
    availability: AvailabilityStatus;
    category: ListingCategory;
    propertyStatus: PropertyStatus;
    location: GeoLocation;
    statusTimestamp: Time;
    images: Array<ExternalBlob>;
}
export interface CreatePaymentResponse {
    checkoutUrl: string;
    sessionId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CityChargeSettings {
    subscription: boolean;
    customerLeadCharge: boolean;
    ownerLeadCharge: boolean;
}
export interface AvailabilityCounts {
    marriageHalls: bigint;
    hotels: bigint;
    pgRooms: bigint;
    familyFlats: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OwnerProfile {
    verified: boolean;
    ownerId: Principal;
    name: string;
    joinedAt: Time;
    email: string;
    contactNumber: string;
}
export interface PaymentSuccessResponse {
    message: string;
    payment: {
        status: string;
        paymentMethod: {
            last4: string;
            brand: string;
        };
        currency: string;
        amount: bigint;
    };
}
export interface QuickPublishResult {
    cacheHits: bigint;
    optimizationCycles: bigint;
    cacheMisses: bigint;
    frontendDeploymentTimeMs: bigint;
    success: boolean;
    backendSyncTimeMs: bigint;
    assetsValidated: bigint;
    assetsCached: bigint;
    buildTimeTotalNs: bigint;
}
export interface PublicListingSubmission {
    ownerId: Principal;
    listingId: bigint;
    ownerProfile: OwnerProfile;
}
export interface AdminNotification {
    id: bigint;
    customerName: string;
    customerPrincipal: Principal;
    read: boolean;
    propertyTitle: string;
    leadId: bigint;
    timestamp: Time;
    category: ListingCategory;
}
export interface PaymentCancelResponse {
    message: string;
    sessionId: string;
}
export interface EventMarker {
    id: bigint;
    createdAt: Time;
    type: string;
    message: string;
    badge: string;
    location: GeoLocation;
}
export interface LeadView {
    id: bigint;
    propertyCategory: ListingCategory;
    propertyArea: string;
    ownerName: string;
    listingId: bigint;
    ownerPrincipal: Principal;
    viewerName: string;
    propertyTitle: string;
    ownerContact: string;
    timestamp: Time;
    viewer: Principal;
}
export interface PublicListingInput {
    ownerEmail: string;
    title: string;
    contactInfo: string;
    ownerName: string;
    description: string;
    pricePerDay: bigint;
    availability: AvailabilityStatus;
    category: ListingCategory;
    location: GeoLocation;
    ownerContactNumber: string;
    images: Array<ExternalBlob>;
}
export interface AvailabilityStatus {
    unitType: string;
    status: Variant_partiallyAvailable_booked_available;
    availableUnits: bigint;
    dates?: Array<{
        date: Time;
        availableUnits: bigint;
    }>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
    registrationDate: Time;
    lastLogin: Time;
    isOwner: boolean;
    location?: GeoLocation;
    ipAddress: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ListingCategory {
    marriageHall = "marriageHall",
    studentStay = "studentStay",
    hotel = "hotel",
    travelStay = "travelStay",
    pgHostel = "pgHostel",
    familyFlat = "familyFlat",
    eventSpace = "eventSpace"
}
export enum PropertyStatus {
    bookedViaSTYO = "bookedViaSTYO",
    available = "available",
    visitCompleted = "visitCompleted",
    underConfirmation = "underConfirmation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_partiallyAvailable_booked_available {
    partiallyAvailable = "partiallyAvailable",
    booked = "booked",
    available = "available"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addReview(listingId: bigint, rating: bigint, comment: string): Promise<bigint>;
    approveListing(_listingId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpdateCityCharges(updates: Array<[string, CityChargeSettings]>): Promise<void>;
    checkoutBookingHold(): Promise<CreatePaymentResponse>;
    checkoutFeaturedListing(): Promise<CreatePaymentResponse>;
    checkoutPropertyListing(): Promise<CreatePaymentResponse>;
    checkoutUnlockOwnerInfo(): Promise<CreatePaymentResponse>;
    createBooking(_listingId: bigint, _checkInDate: Time, _checkOutDate: Time): Promise<bigint>;
    createListing(_title: string, _description: string, _category: ListingCategory, _pricePerDay: bigint, _images: Array<ExternalBlob>, _location: GeoLocation, _availability: AvailabilityStatus, _contactInfo: string): Promise<bigint>;
    createOwnerUnlockRequest(_listingId: bigint): Promise<bigint>;
    getAdminDashboardData(): Promise<{
        leadViews: Array<LeadView>;
        notifications: Array<AdminNotification>;
        listings: Array<Listing>;
        users: Array<UserProfile>;
        cityCharges: Array<[string, CityChargeSettings]>;
    }>;
    getAdminNotifications(): Promise<Array<AdminNotification>>;
    getAllListingsForReview(): Promise<Array<Listing>>;
    getAvailability(id: bigint): Promise<AvailabilityStatus | null>;
    getAvailabilityCounts(): Promise<AvailabilityCounts>;
    getAvailableListings(): Promise<Array<Listing>>;
    getAverageRating(listingId: bigint): Promise<number | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChargeStatusForCity(city: string): Promise<CityChargeSettings>;
    getCityChargeSettings(): Promise<Array<[string, CityChargeSettings]>>;
    getEventMarkers(): Promise<Array<EventMarker>>;
    getFeaturedListings(): Promise<Array<Listing>>;
    getLeadAnalytics(): Promise<Array<LeadView>>;
    getListing(id: bigint): Promise<Listing | null>;
    getListings(): Promise<Array<Listing>>;
    getListingsByApprovalStatus(status: ApprovalStatus): Promise<Array<Listing>>;
    getListingsByCategory(category: ListingCategory): Promise<Array<Listing>>;
    getListingsByLocation(lat: number, lon: number, radius: number | null): Promise<Array<Listing>>;
    getPendingSubmissions(): Promise<Array<[bigint, PublicListingSubmission]>>;
    getReviewsForListing(listingId: bigint): Promise<Array<Review>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVerifiedListings(): Promise<Array<Listing>>;
    initializeStripePrices(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isFreeTrialMode(): Promise<boolean>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    paymentCancel(sessionId: string): Promise<PaymentCancelResponse>;
    paymentSuccess(sessionId: string, accountId: string, caffeineCustomerId: string): Promise<PaymentSuccessResponse>;
    processExpiredListings(): Promise<bigint>;
    quickPublishMode(): Promise<QuickPublishResult>;
    rejectListing(_listingId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setFreeTrialMode(enable: boolean): Promise<void>;
    submitPublicListing(listing: PublicListingInput): Promise<bigint>;
    updateAvailability(_listingId: bigint, _availability: AvailabilityStatus): Promise<void>;
    updateCityChargeSettings(city: string, settings: CityChargeSettings): Promise<void>;
    updateListing(_id: bigint, _listing: Listing): Promise<void>;
    updateOwnerProfile(_profile: OwnerProfile): Promise<void>;
    updatePropertyStatus(_listingId: bigint, newStatus: PropertyStatus): Promise<void>;
    verifyListing(_listingId: bigint, _verified: boolean): Promise<void>;
}
import type { AdminNotification as _AdminNotification, ApprovalStatus as _ApprovalStatus, AvailabilityStatus as _AvailabilityStatus, CityChargeSettings as _CityChargeSettings, ExternalBlob as _ExternalBlob, GeoLocation as _GeoLocation, LeadView as _LeadView, Listing as _Listing, ListingCategory as _ListingCategory, PropertyStatus as _PropertyStatus, PublicListingInput as _PublicListingInput, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addReview(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2);
            return result;
        }
    }
    async approveListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveListing(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpdateCityCharges(arg0: Array<[string, CityChargeSettings]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateCityCharges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateCityCharges(arg0);
            return result;
        }
    }
    async checkoutBookingHold(): Promise<CreatePaymentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutBookingHold();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutBookingHold();
            return result;
        }
    }
    async checkoutFeaturedListing(): Promise<CreatePaymentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutFeaturedListing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutFeaturedListing();
            return result;
        }
    }
    async checkoutPropertyListing(): Promise<CreatePaymentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutPropertyListing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutPropertyListing();
            return result;
        }
    }
    async checkoutUnlockOwnerInfo(): Promise<CreatePaymentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutUnlockOwnerInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutUnlockOwnerInfo();
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: Time, arg2: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2);
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: ListingCategory, arg3: bigint, arg4: Array<ExternalBlob>, arg5: GeoLocation, arg6: AvailabilityStatus, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_AvailabilityStatus_n14(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_AvailabilityStatus_n14(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async createOwnerUnlockRequest(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOwnerUnlockRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOwnerUnlockRequest(arg0);
            return result;
        }
    }
    async getAdminDashboardData(): Promise<{
        leadViews: Array<LeadView>;
        notifications: Array<AdminNotification>;
        listings: Array<Listing>;
        users: Array<UserProfile>;
        cityCharges: Array<[string, CityChargeSettings]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardData();
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardData();
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminNotifications(): Promise<Array<AdminNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminNotifications();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminNotifications();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListingsForReview(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListingsForReview();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListingsForReview();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailability(arg0: bigint): Promise<AvailabilityStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailability(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailability(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailabilityCounts(): Promise<AvailabilityCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailabilityCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailabilityCounts();
            return result;
        }
    }
    async getAvailableListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableListings();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableListings();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageRating(arg0: bigint): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChargeStatusForCity(arg0: string): Promise<CityChargeSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getChargeStatusForCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChargeStatusForCity(arg0);
            return result;
        }
    }
    async getCityChargeSettings(): Promise<Array<[string, CityChargeSettings]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCityChargeSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCityChargeSettings();
            return result;
        }
    }
    async getEventMarkers(): Promise<Array<EventMarker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventMarkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventMarkers();
            return result;
        }
    }
    async getFeaturedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedListings();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedListings();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadAnalytics(): Promise<Array<LeadView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadAnalytics();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadAnalytics();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: bigint): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsByApprovalStatus(arg0: ApprovalStatus): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByApprovalStatus(to_candid_ApprovalStatus_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByApprovalStatus(to_candid_ApprovalStatus_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsByCategory(arg0: ListingCategory): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByCategory(to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByCategory(to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsByLocation(arg0: number, arg1: number, arg2: number | null): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByLocation(arg0, arg1, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByLocation(arg0, arg1, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingSubmissions(): Promise<Array<[bigint, PublicListingSubmission]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSubmissions();
            return result;
        }
    }
    async getReviewsForListing(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForListing(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedListings();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedListings();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeStripePrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeStripePrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeStripePrices();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFreeTrialMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFreeTrialMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFreeTrialMode();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async paymentCancel(arg0: string): Promise<PaymentCancelResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentCancel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentCancel(arg0);
            return result;
        }
    }
    async paymentSuccess(arg0: string, arg1: string, arg2: string): Promise<PaymentSuccessResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
            return result;
        }
    }
    async processExpiredListings(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.processExpiredListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processExpiredListings();
            return result;
        }
    }
    async quickPublishMode(): Promise<QuickPublishResult> {
        if (this.processError) {
            try {
                const result = await this.actor.quickPublishMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.quickPublishMode();
            return result;
        }
    }
    async rejectListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectListing(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setFreeTrialMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFreeTrialMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFreeTrialMode(arg0);
            return result;
        }
    }
    async submitPublicListing(arg0: PublicListingInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPublicListing(await to_candid_PublicListingInput_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPublicListing(await to_candid_PublicListingInput_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAvailability(arg0: bigint, arg1: AvailabilityStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvailability(arg0, to_candid_AvailabilityStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvailability(arg0, to_candid_AvailabilityStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCityChargeSettings(arg0: string, arg1: CityChargeSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCityChargeSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCityChargeSettings(arg0, arg1);
            return result;
        }
    }
    async updateListing(arg0: bigint, arg1: Listing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, await to_candid_Listing_n56(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, await to_candid_Listing_n56(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOwnerProfile(arg0: OwnerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOwnerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOwnerProfile(arg0);
            return result;
        }
    }
    async updatePropertyStatus(arg0: bigint, arg1: PropertyStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePropertyStatus(arg0, to_candid_PropertyStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePropertyStatus(arg0, to_candid_PropertyStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyListing(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyListing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyListing(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AdminNotification_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminNotification): AdminNotification {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_AvailabilityStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityStatus): AvailabilityStatus {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LeadView_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadView): LeadView {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ListingCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingCategory): ListingCategory {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyStatus): PropertyStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<{
        date: _Time;
        availableUnits: bigint;
    }>]): Array<{
    date: Time;
    availableUnits: bigint;
}> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeoLocation]): GeoLocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AvailabilityStatus]): AvailabilityStatus | null {
    return value.length === 0 ? null : from_candid_AvailabilityStatus_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n40(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Promise<Listing | null> {
    return value.length === 0 ? null : await from_candid_Listing_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadViews: Array<_LeadView>;
    notifications: Array<_AdminNotification>;
    listings: Array<_Listing>;
    users: Array<_UserProfile>;
    cityCharges: Array<[string, _CityChargeSettings]>;
}): Promise<{
    leadViews: Array<LeadView>;
    notifications: Array<AdminNotification>;
    listings: Array<Listing>;
    users: Array<UserProfile>;
    cityCharges: Array<[string, CityChargeSettings]>;
}> {
    return {
        leadViews: from_candid_vec_n18(_uploadFile, _downloadFile, value.leadViews),
        notifications: from_candid_vec_n23(_uploadFile, _downloadFile, value.notifications),
        listings: await from_candid_vec_n26(_uploadFile, _downloadFile, value.listings),
        users: from_candid_vec_n39(_uploadFile, _downloadFile, value.users),
        cityCharges: value.cityCharges
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    propertyCategory: _ListingCategory;
    propertyArea: string;
    ownerName: string;
    listingId: bigint;
    ownerPrincipal: Principal;
    viewerName: string;
    propertyTitle: string;
    ownerContact: string;
    timestamp: _Time;
    viewer: Principal;
}): {
    id: bigint;
    propertyCategory: ListingCategory;
    propertyArea: string;
    ownerName: string;
    listingId: bigint;
    ownerPrincipal: Principal;
    viewerName: string;
    propertyTitle: string;
    ownerContact: string;
    timestamp: Time;
    viewer: Principal;
} {
    return {
        id: value.id,
        propertyCategory: from_candid_ListingCategory_n21(_uploadFile, _downloadFile, value.propertyCategory),
        propertyArea: value.propertyArea,
        ownerName: value.ownerName,
        listingId: value.listingId,
        ownerPrincipal: value.ownerPrincipal,
        viewerName: value.viewerName,
        propertyTitle: value.propertyTitle,
        ownerContact: value.ownerContact,
        timestamp: value.timestamp,
        viewer: value.viewer
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    customerPrincipal: Principal;
    read: boolean;
    propertyTitle: string;
    leadId: bigint;
    timestamp: _Time;
    category: _ListingCategory;
}): {
    id: bigint;
    customerName: string;
    customerPrincipal: Principal;
    read: boolean;
    propertyTitle: string;
    leadId: bigint;
    timestamp: Time;
    category: ListingCategory;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        customerPrincipal: value.customerPrincipal,
        read: value.read,
        propertyTitle: value.propertyTitle,
        leadId: value.leadId,
        timestamp: value.timestamp,
        category: from_candid_ListingCategory_n21(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    verified: boolean;
    featured: boolean;
    contactInfo: string;
    owner: Principal;
    createdAt: _Time;
    lastUpdated: _Time;
    description: string;
    approvalStatus: _ApprovalStatus;
    pricePerDay: bigint;
    availability: _AvailabilityStatus;
    category: _ListingCategory;
    propertyStatus: _PropertyStatus;
    location: _GeoLocation;
    statusTimestamp: _Time;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    title: string;
    verified: boolean;
    featured: boolean;
    contactInfo: string;
    owner: Principal;
    createdAt: Time;
    lastUpdated: Time;
    description: string;
    approvalStatus: ApprovalStatus;
    pricePerDay: bigint;
    availability: AvailabilityStatus;
    category: ListingCategory;
    propertyStatus: PropertyStatus;
    location: GeoLocation;
    statusTimestamp: Time;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        verified: value.verified,
        featured: value.featured,
        contactInfo: value.contactInfo,
        owner: value.owner,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        description: value.description,
        approvalStatus: from_candid_ApprovalStatus_n29(_uploadFile, _downloadFile, value.approvalStatus),
        pricePerDay: value.pricePerDay,
        availability: from_candid_AvailabilityStatus_n31(_uploadFile, _downloadFile, value.availability),
        category: from_candid_ListingCategory_n21(_uploadFile, _downloadFile, value.category),
        propertyStatus: from_candid_PropertyStatus_n35(_uploadFile, _downloadFile, value.propertyStatus),
        location: value.location,
        statusTimestamp: value.statusTimestamp,
        images: await from_candid_vec_n37(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unitType: string;
    status: {
        partiallyAvailable: null;
    } | {
        booked: null;
    } | {
        available: null;
    };
    availableUnits: bigint;
    dates: [] | [Array<{
            date: _Time;
            availableUnits: bigint;
        }>];
}): {
    unitType: string;
    status: Variant_partiallyAvailable_booked_available;
    availableUnits: bigint;
    dates?: Array<{
        date: Time;
        availableUnits: bigint;
    }>;
} {
    return {
        unitType: value.unitType,
        status: from_candid_variant_n33(_uploadFile, _downloadFile, value.status),
        availableUnits: value.availableUnits,
        dates: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.dates))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    phone: string;
    registrationDate: _Time;
    lastLogin: _Time;
    isOwner: boolean;
    location: [] | [_GeoLocation];
    ipAddress: string;
}): {
    name: string;
    email: string;
    phone: string;
    registrationDate: Time;
    lastLogin: Time;
    isOwner: boolean;
    location?: GeoLocation;
    ipAddress: string;
} {
    return {
        name: value.name,
        email: value.email,
        phone: value.phone,
        registrationDate: value.registrationDate,
        lastLogin: value.lastLogin,
        isOwner: value.isOwner,
        location: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.location)),
        ipAddress: value.ipAddress
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marriageHall: null;
} | {
    studentStay: null;
} | {
    hotel: null;
} | {
    travelStay: null;
} | {
    pgHostel: null;
} | {
    familyFlat: null;
} | {
    eventSpace: null;
}): ListingCategory {
    return "marriageHall" in value ? ListingCategory.marriageHall : "studentStay" in value ? ListingCategory.studentStay : "hotel" in value ? ListingCategory.hotel : "travelStay" in value ? ListingCategory.travelStay : "pgHostel" in value ? ListingCategory.pgHostel : "familyFlat" in value ? ListingCategory.familyFlat : "eventSpace" in value ? ListingCategory.eventSpace : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    partiallyAvailable: null;
} | {
    booked: null;
} | {
    available: null;
}): Variant_partiallyAvailable_booked_available {
    return "partiallyAvailable" in value ? Variant_partiallyAvailable_booked_available.partiallyAvailable : "booked" in value ? Variant_partiallyAvailable_booked_available.booked : "available" in value ? Variant_partiallyAvailable_booked_available.available : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookedViaSTYO: null;
} | {
    available: null;
} | {
    visitCompleted: null;
} | {
    underConfirmation: null;
}): PropertyStatus {
    return "bookedViaSTYO" in value ? PropertyStatus.bookedViaSTYO : "available" in value ? PropertyStatus.available : "visitCompleted" in value ? PropertyStatus.visitCompleted : "underConfirmation" in value ? PropertyStatus.underConfirmation : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeadView>): Array<LeadView> {
    return value.map((x)=>from_candid_LeadView_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminNotification>): Array<AdminNotification> {
    return value.map((x)=>from_candid_AdminNotification_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n40(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_AvailabilityStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): _AvailabilityStatus {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): _ListingCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_Listing_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Listing): Promise<_Listing> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): _PropertyStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_PublicListingInput_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicListingInput): Promise<_PublicListingInput> {
    return await to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unitType: string;
    status: Variant_partiallyAvailable_booked_available;
    availableUnits: bigint;
    dates?: Array<{
        date: Time;
        availableUnits: bigint;
    }>;
}): {
    unitType: string;
    status: {
        partiallyAvailable: null;
    } | {
        booked: null;
    } | {
        available: null;
    };
    availableUnits: bigint;
    dates: [] | [Array<{
            date: _Time;
            availableUnits: bigint;
        }>];
} {
    return {
        unitType: value.unitType,
        status: to_candid_variant_n16(_uploadFile, _downloadFile, value.status),
        availableUnits: value.availableUnits,
        dates: value.dates ? candid_some(value.dates) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    phone: string;
    registrationDate: Time;
    lastLogin: Time;
    isOwner: boolean;
    location?: GeoLocation;
    ipAddress: string;
}): {
    name: string;
    email: string;
    phone: string;
    registrationDate: _Time;
    lastLogin: _Time;
    isOwner: boolean;
    location: [] | [_GeoLocation];
    ipAddress: string;
} {
    return {
        name: value.name,
        email: value.email,
        phone: value.phone,
        registrationDate: value.registrationDate,
        lastLogin: value.lastLogin,
        isOwner: value.isOwner,
        location: value.location ? candid_some(value.location) : candid_none(),
        ipAddress: value.ipAddress
    };
}
async function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ownerEmail: string;
    title: string;
    contactInfo: string;
    ownerName: string;
    description: string;
    pricePerDay: bigint;
    availability: AvailabilityStatus;
    category: ListingCategory;
    location: GeoLocation;
    ownerContactNumber: string;
    images: Array<ExternalBlob>;
}): Promise<{
    ownerEmail: string;
    title: string;
    contactInfo: string;
    ownerName: string;
    description: string;
    pricePerDay: bigint;
    availability: _AvailabilityStatus;
    category: _ListingCategory;
    location: _GeoLocation;
    ownerContactNumber: string;
    images: Array<_ExternalBlob>;
}> {
    return {
        ownerEmail: value.ownerEmail,
        title: value.title,
        contactInfo: value.contactInfo,
        ownerName: value.ownerName,
        description: value.description,
        pricePerDay: value.pricePerDay,
        availability: to_candid_AvailabilityStatus_n14(_uploadFile, _downloadFile, value.availability),
        category: to_candid_ListingCategory_n10(_uploadFile, _downloadFile, value.category),
        location: value.location,
        ownerContactNumber: value.ownerContactNumber,
        images: await to_candid_vec_n12(_uploadFile, _downloadFile, value.images)
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    verified: boolean;
    featured: boolean;
    contactInfo: string;
    owner: Principal;
    createdAt: Time;
    lastUpdated: Time;
    description: string;
    approvalStatus: ApprovalStatus;
    pricePerDay: bigint;
    availability: AvailabilityStatus;
    category: ListingCategory;
    propertyStatus: PropertyStatus;
    location: GeoLocation;
    statusTimestamp: Time;
    images: Array<ExternalBlob>;
}): Promise<{
    id: bigint;
    title: string;
    verified: boolean;
    featured: boolean;
    contactInfo: string;
    owner: Principal;
    createdAt: _Time;
    lastUpdated: _Time;
    description: string;
    approvalStatus: _ApprovalStatus;
    pricePerDay: bigint;
    availability: _AvailabilityStatus;
    category: _ListingCategory;
    propertyStatus: _PropertyStatus;
    location: _GeoLocation;
    statusTimestamp: _Time;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        verified: value.verified,
        featured: value.featured,
        contactInfo: value.contactInfo,
        owner: value.owner,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        description: value.description,
        approvalStatus: to_candid_ApprovalStatus_n49(_uploadFile, _downloadFile, value.approvalStatus),
        pricePerDay: value.pricePerDay,
        availability: to_candid_AvailabilityStatus_n14(_uploadFile, _downloadFile, value.availability),
        category: to_candid_ListingCategory_n10(_uploadFile, _downloadFile, value.category),
        propertyStatus: to_candid_PropertyStatus_n58(_uploadFile, _downloadFile, value.propertyStatus),
        location: value.location,
        statusTimestamp: value.statusTimestamp,
        images: await to_candid_vec_n12(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): {
    marriageHall: null;
} | {
    studentStay: null;
} | {
    hotel: null;
} | {
    travelStay: null;
} | {
    pgHostel: null;
} | {
    familyFlat: null;
} | {
    eventSpace: null;
} {
    return value == ListingCategory.marriageHall ? {
        marriageHall: null
    } : value == ListingCategory.studentStay ? {
        studentStay: null
    } : value == ListingCategory.hotel ? {
        hotel: null
    } : value == ListingCategory.travelStay ? {
        travelStay: null
    } : value == ListingCategory.pgHostel ? {
        pgHostel: null
    } : value == ListingCategory.familyFlat ? {
        familyFlat: null
    } : value == ListingCategory.eventSpace ? {
        eventSpace: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_partiallyAvailable_booked_available): {
    partiallyAvailable: null;
} | {
    booked: null;
} | {
    available: null;
} {
    return value == Variant_partiallyAvailable_booked_available.partiallyAvailable ? {
        partiallyAvailable: null
    } : value == Variant_partiallyAvailable_booked_available.booked ? {
        booked: null
    } : value == Variant_partiallyAvailable_booked_available.available ? {
        available: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): {
    bookedViaSTYO: null;
} | {
    available: null;
} | {
    visitCompleted: null;
} | {
    underConfirmation: null;
} {
    return value == PropertyStatus.bookedViaSTYO ? {
        bookedViaSTYO: null
    } : value == PropertyStatus.available ? {
        available: null
    } : value == PropertyStatus.visitCompleted ? {
        visitCompleted: null
    } : value == PropertyStatus.underConfirmation ? {
        underConfirmation: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
